service: my-express-application

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: us-east-1

functions:
  app:
    handler: index.handler
    environment:
      IN_LAMBDA: 'true'
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'
