service: my-express-application

package:
  exclude:
  - coverage/**
  - .circleci/**
  - src/**
  - .git/**

provider:
  name: aws
  runtime: nodejs6.10
  stage: ${opt:stage, 'dev'}
  region: us-east-1

functions:
  app:
    handler: index.handler
    environment:
      IN_LAMBDA: 'true'
      BUNDLE_URL: https://s3-us-west-2.amazonaws.com/${env:ASSETS_BUCKET}/${opt:bundleName, 'bundle.js'}
      CSS_BUNDLE_URL: https://s3-us-west-2.amazonaws.com/${env:ASSETS_BUCKET}/${opt:cssBundleName, 'main.css'}
      PATH_BASE: 'dev'
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'
